---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.deployname}}
  labels:
    {{include "dr-project.labels" . | trim | nindent 4}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      instance: {{.Values.instancevalue}}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'true'
      labels: 
       {{- include "dr-project.deploymentlabel" . | trim | nindent 8}}
    spec:
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{.Values.deployname}}
          image: "{{.Values.image.repository}}:{{.Values.image.tag}}"
          imagePullPolicy: {{.Values.image.pullPolicy}}
          ports:
            - containerPort: {{.Values.service.port}}
          resources:
            {{- toYaml .Values.resources | trim | nindent 12}}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | trim | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | trim | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | trim | nindent 8 }}
      {{- end }}
